config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root "pets#index"
  resources :pets
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :rooms, only: [:create, :show, :index]
end

app/models/pet.rb
class Pet < ApplicationRecord
  scope :kind_like, -> kind {where('kind like ?', "%#{kind}%")}
  scope :prefecture_match, -> (params) {where(prefecture: (params))}
  mount_uploader :image, ImageUploader
  validates :status, presence: true
  validates :kind, presence: true
  validates :feature, presence: true
  validates :image, presence: true
  validates :prefecture, presence: true
  validates :place, presence: true
  validates :area, presence: true
  validate :lost_day_cannot_be_in_the_future
  validate :find_day_cannot_be_in_the_future
  def lost_day_cannot_be_in_the_future
    if lost_day.present? && Date.today < lost_day
      errors.add(:lost_day, "は未来の日時は選択できません")
    end
  end
  def find_day_cannot_be_in_the_future
    if find_day.present? && Date.today < find_day
      errors.add(:find_day, "は未来の日時は選択できません")
    end
  end
  belongs_to :user
  mount_uploader :image, ImageUploader
  enum prefecture:{
      "都道府県を選択":0,
      北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
      茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
      新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
      岐阜県:21,静岡県:22,愛知県:23,三重県:24,
      滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
      鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
      徳島県:36,香川県:37,愛媛県:38,高知県:39,
      福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
      沖縄県:47
  }
  enum status:{
    すべてのステータス:0,
    迷子:1,
    保護:2
  }
  geocoded_by :area
  after_validation :geocode, if: :area_changed?
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  PER = 9
  def index
    pet_page = Pet.page(params[:page]).includes(:user).per(PER).order(created_at: "DESC")
    if params[:keyword].present? && params[:prefecture] != "都道府県を選択" && params[:prefecture].present? && params[:status] == "迷子"
      @pets = pet_page.kind_like(params[:keyword]).prefecture_match(params[:prefecture]).where(status: "迷子")
    elsif params[:keyword].present? && params[:prefecture] != "都道府県を選択" && params[:prefecture].present? && params[:status] == "保護"
      @pets = pet_page.kind_like(params[:keyword]).prefecture_match(params[:prefecture]).where(status: "保護")
    elsif params[:keyword].present? && params[:prefecture] != "都道府県を選択" && params[:prefecture].present? && params[:status] == "すべてのステータス"
      @pets = pet_page.kind_like(params[:keyword]).prefecture_match(params[:prefecture])
    elsif params[:keyword].present? && params[:prefecture] != "都道府県を選択" && params[:status] == "迷子"
      @pets = pet_page.kind_like(params[:keyword]).where(status: "迷子")
    elsif params[:keyword].present? && params[:prefecture] != "都道府県を選択" && params[:status] == "保護"
      @pets = pet_page.kind_like(params[:keyword]).where(status: "保護")
    elsif params[:keyword].present? && params[:prefecture] != "都道府県を選択" && params[:status] == "すべてのステータス"
      @pets = pet_page.kind_like(params[:keyword]).order(created_at: "DESC")
    elsif params[:prefecture].present? && params[:prefecture] != "都道府県を選択" && params[:status] == "迷子"
      @pets = pet_page.prefecture_match(params[:prefecture]).where(status: "迷子")
    elsif params[:prefecture].present? && params[:prefecture] != "都道府県を選択" && params[:status] == "保護"
      @pets = pet_page.prefecture_match(params[:prefecture]).where(status: "保護")
    elsif params[:prefecture].present? && params[:prefecture] != "都道府県を選択" && params[:status] == "すべてのステータス"
      @pets = pet_page.prefecture_match(params[:prefecture])
    elsif params[:status] == "保護"
      @pets = pet_page.where(status: "保護")
    elsif params[:status] == "迷子"
      @pets = pet_page.where(status: "迷子")
    else
      @pets = pet_page.all.per(PER)
    end
  end

  def new
    if user_signed_in?
      @pet = Pet.new
    else
      flash[:info] = "ユーザー登録が必要です"
      redirect_to new_user_registration_path
    end
  end
  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id
    @pet.area = params[:pet][:prefecture].to_s + " " + params[:pet][:place].to_s
    if @pet.save
      flash[:success] = "保存しました"
      redirect_to pets_path
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.area = params[:pet][:prefecture].to_s + " " + params[:pet][:place].to_s
    if @pet.update(pet_params)
      flash[:success] = "ペット情報を編集しました！"
      redirect_to pet_path(@pet.id)
    else
      render :edit
    end
  end

  def show
    @pet = Pet.find(params[:id])
    @user = @pet.user
    if user_signed_in?
      @currentUserEntry = Entry.where(user_id: current_user.id)
      @userEntry = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
        unless @isRoom
          @room = Room.new
          @entry = Entry.new
        end
      end
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    if @pet.destroy
      flash[:success] = "ペット情報を削除しました！"
      redirect_to pets_path
    else
      flash[:success] = "削除に失敗しました。"
      redirect_to pets_path
    end
  end


  private
  def pet_params
    params.require(:pet).permit(:name, :kind, :lost_gender,:find_gender, :feature, :photo, :status, :find_day, :lost_day, :wanted, :image, :image_cache, :latitude, :longitude, :prefecture, :place, :area)
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/edit.html.erb
<div class="col-sm-12" id="form-page">
  <div id="breadcrumb">
    <% breadcrumb :edit_pet %>
    <%= render "shared/breadcrumbs" %>
  </div>
<% if @pet.errors.any? %>
  <div id="error_explanation">
    <h2><%= @pet.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @pet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1>ペット編集</h1>
<%= form_with(model: @pet, local: true, class: 'form-inline') do |f| %>

  <div id="tr0">
    <h2>迷子 or 保護<span class="red">*</span></h2>
    <p>
      <%= f.radio_button :status, Pet.statuses.keys[1], class: "lost_or_rescued" %>
      <%= f.label "迷子" %>
      <%= f.radio_button :status, Pet.statuses.keys[2], class: "lost_or_rescued" %>
      <%= f.label "保護" %>
    </p>
  </div>

  <div id="tr1">
    <h2>ペットの名前</h2>
    <p><%= f.text_field :name, placeholder: "小太郎", class: "form-control" %></p>
    <h2>ペットの種類<span class="red">*</span></h2>
    <p><%= f.text_field :kind, placeholder: "オカメインコ", class: "form-control" %></p>

    <h2>性別<span class="red">*</span></h2>
    <p>
      <%= f.radio_button :lost_gender, :オス, checked: true, class: 'form-control' %>
      <%= f.label "オス" %>
      <%= f.radio_button :lost_gender, :メス, class: 'form-control' %>
      <%= f.label "メス" %>
      <%= f.radio_button :lost_gender, :不明, class: 'form-control' %>
      <%= f.label "不明" %>
    </p>

    <h2>迷子になった日<span class="red">*</span></h2>
    <p><%= f.date_select :lost_day, {}, class: 'form-control' %></p>
    <h2>ペットの写真<span class="red">*</span></h2>
    <%= image_tag(@pet.image.url) if @pet.image && @pet.image.url %>
    <p><%= f.file_field :image, class: 'form-control-file' %></p>
    <%= f.hidden_field :image_cache %>
    <h2>迷子になった場所<span class="red">*</span></h2>
    <p>
      <%= f.select :prefecture, Pet.prefectures.keys, {}, class: 'form-control col-md-4' %>
      <%= f.text_field :place, placeholder: "淵野辺公園", class: "form-control col-md-4" %>
    </p>
    <h2>ペットの詳細<span class="red">*</span></h2>
    <%= f.text_area :feature, placeholder: "説明文入ります。", class: "form-control" %>
    <div class="btn_group clearfix">
      <p class="btn_save"><%= f.submit "保存", class: "btn btn-primary" %></p>
      <p class="btn_cancel"><%= link_to "キャンセル", :back, class: "btn btn-light" %></p>
    </div>
  </div>

  <div id="tr2">
    <h2>ペットの種類<span class="red">*</span></h2>
    <p><%= f.text_field :kind, placeholder: "オカメインコ", class: "form-control" %></p>
    <h2>性別<span class="red">*</span></h2>
    <%= f.radio_button :find_gender, :オス, class: 'form-control' %>
    <%= f.label "オス" %>
    <%= f.radio_button :find_gender, :メス, checked: true, class: 'form-control' %>
    <%= f.label "メス" %>
    <%= f.radio_button :find_gender, :不明, class: 'form-control' %>
    <%= f.label "不明" %>

    <h2>保護した日<span class="red">*</span></h2>
    <%= f.date_select :find_day, {}, class: 'form-control' %>
    <h2>ペットの写真<span class="red">*</span></h2>
    <%= image_tag(@pet.image.url) if @pet.image && @pet.image.url %>
    <%= f.file_field :image, class: 'form-control-file' %>
    <%= f.hidden_field :image_cache %>
    <h2>保護した場所<span class="red">*</span></h2>
    <%= f.select :prefecture, Pet.prefectures.keys, {}, class: 'form-control col-md-4' %>
    <%= f.text_field :place, placeholder: "淵野辺公園", class: "form-control col-md-4" %>
    <h2>ペットの詳細<span class="red">*</span></h2>
    <%= f.text_area :feature, placeholder: "説明文入ります。", class: "form-control" %>
    <div class="btn_group clearfix">
      <p class="btn_save"><%= f.submit "保存", class: "btn btn-primary" %></p>
      <p class="btn_cancel"><%= link_to "キャンセル", :back, class: "btn btn-light" %></p>
    </div>
  </div>
<% end %>

</div>

<script type="text/javascript">
$(function() {
    $('input[type=radio]').change(function() {
        $('#tr1,#tr2').removeClass('invisible');
        if ($("input:radio[class='lost_or_rescued']:checked").val() == "迷子") {
            $('#tr2').addClass('invisible');
            $('#tr2 .form-control').prop('disabled', true);
            $('#tr1 .form-control').prop('disabled', false);
        } else if($("input:radio[class='lost_or_rescued']:checked").val() == "保護") {
            $('#tr1').addClass('invisible');
            $('#tr1 .form-control').prop('disabled', true);
            $('#tr2 .form-control').prop('disabled', false);
        }
    }).trigger('change'); //←(1)
});
</script>

app/views/pets/index.html.erb
  <div class="col-sm-12">
    <div class="float-right">

      <p id="addpet">
        <%= link_to new_pet_path do %>
          <i class="material-icons-round">add</i>ペットを登録
        <% end %>
      </p>
    </div>

    <div id="searchbox">
      <%= form_with(url: pets_path, local: true, method: :get, class: 'form-inline') do |f| %>
        <%= f.select :status, Pet.statuses.keys.to_a, {selected: params[:status]}, class: 'form-control' %>
        <%= f.select :prefecture, Pet.prefectures.keys.to_a, {selected: params[:prefecture]}, class: 'form-control' %>
        <%= f.text_field :keyword, id: "kind_name", placeholder: "種類、例：オカメインコ", value: params[:keyword], class: 'form-control' %>
        <%= f.submit '検索', class: "decision btn btn-info" %>
      <% end %>
    </div>
  </div>

  <% @pets.each do |pet| %>
  <div class="col-sm-12 col-md-4 pet-unit">
    <p class="img-fluid"><%= link_to image_tag(pet.image.url, class: "img-fluid"), pet_path(pet.id) %></p>
    <div>
    <p class="pet_kind">
      <% if pet.status == "迷子" %>
        <%= link_to pet.status, pet_path(pet.id), class: "status status_lost" %>
      <% elsif pet.status == "保護" %>
        <%= link_to pet.status, pet_path(pet.id), class: "status status_find" %>
      <% end %>
       <%= link_to pet.kind, pet_path(pet.id) %></p>
    <p class="pet_area"><i class="material-icons-round">place</i>
      <%= link_to pet.area, pet_path(pet.id) %></p>
    <p class="pet_created_at"><i class="material-icons-round">access_time</i> <%= link_to pet.created_at.strftime("%Y年%m月%d日 %H:%M"), pet_path(pet.id) %></p>
    </div>
  </div>
  <% end %>

  <div class="col-sm-12">
    <%= paginate @pets, class: "btn" %>
  </div>

app/views/pets/new.html.erb
<div class="col-sm-12" id="form-page">
  <div id="breadcrumb">
    <% breadcrumb :new_pet %>
    <%= render "shared/breadcrumbs" %>
  </div>
<% if @pet.errors.any? %>
  <div id="error_explanation">
    <h2><%= @pet.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @pet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1>ペット登録</h1>
<%= form_with(model: @pet, local: true, class: 'form-inline') do |f| %>

  <div id="tr0">
    <h2>迷子 or 保護<span class="red">*</span></h2>
    <p>
      <%= f.radio_button :status, Pet.statuses.keys[1], class: "lost_or_rescued" %>
      <%= f.label "迷子" %>
      <%= f.radio_button :status, Pet.statuses.keys[2], class: "lost_or_rescued" %>
      <%= f.label "保護" %>
    </p>
  </div>

  <div id="tr1">
    <h2>ペットの名前</h2>
    <p><%= f.text_field :name, placeholder: "小太郎", class: "form-control" %></p>
    <h2>ペットの種類<span class="red">*</span></h2>
    <p><%= f.text_field :kind, placeholder: "オカメインコ", class: "form-control" %></p>

    <h2>性別<span class="red">*</span></h2>
    <p>
      <%= f.radio_button :lost_gender, :オス, checked: true, class: 'form-control' %>
      <%= f.label "オス" %>
      <%= f.radio_button :lost_gender, :メス, class: 'form-control' %>
      <%= f.label "メス" %>
      <%= f.radio_button :lost_gender, :不明, class: 'form-control' %>
      <%= f.label "不明" %>
    </p>

    <h2>迷子になった日<span class="red">*</span></h2>
    <p><%= f.date_select :lost_day, {}, class: 'form-control' %></p>
    <h2>ペットの写真<span class="red">*</span></h2>
    <%= image_tag(@pet.image.url) if @pet.image && @pet.image.url %>
    <p><%= f.file_field :image, class: 'form-control-file' %></p>
    <%= f.hidden_field :image_cache %>
    <h2>迷子になった場所<span class="red">*</span></h2>
    <p>
      <%= f.select :prefecture, Pet.prefectures.keys, {}, class: 'form-control col-md-4' %>
      <%= f.text_field :place, placeholder: "淵野辺公園", class: "form-control col-md-4" %>
    </p>
    <h2>ペットの詳細<span class="red">*</span></h2>
    <%= f.text_area :feature, placeholder: "説明文入ります。", class: "form-control" %>
    <div class="btn_group clearfix">
      <p class="btn_save"><%= f.submit "保存", class: "btn btn-primary" %></p>
      <p class="btn_cancel"><%= link_to "キャンセル", :back, class: "btn btn-light" %></p>
    </div>
  </div>

  <div id="tr2">
    <h2>ペットの種類<span class="red">*</span></h2>
    <p><%= f.text_field :kind, placeholder: "オカメインコ", class: "form-control" %></p>
    <h2>性別<span class="red">*</span></h2>
    <%= f.radio_button :find_gender, :オス, checked: true, class: 'form-control' %>
    <%= f.label "オス" %>
    <%= f.radio_button :find_gender, :メス, class: 'form-control' %>
    <%= f.label "メス" %>
    <%= f.radio_button :find_gender, :不明, class: 'form-control' %>
    <%= f.label "不明" %>

    <h2>保護した日<span class="red">*</span></h2>
    <%= f.date_select :find_day, {}, class: 'form-control' %>
    <h2>ペットの写真<span class="red">*</span></h2>
    <%= image_tag(@pet.image.url) if @pet.image && @pet.image.url %>
    <%= f.file_field :image, class: 'form-control-file' %>
    <%= f.hidden_field :image_cache %>
    <h2>保護した場所<span class="red">*</span></h2>
    <%= f.select :prefecture, Pet.prefectures.keys, {}, class: 'form-control col-md-4' %>
    <%= f.text_field :place, placeholder: "淵野辺公園", class: "form-control col-md-4" %>
    <h2>ペットの詳細<span class="red">*</span></h2>
    <%= f.text_area :feature, placeholder: "説明文入ります。", class: "form-control" %>
    <div class="btn_group clearfix">
      <p class="btn_save"><%= f.submit "保存", class: "btn btn-primary" %></p>
      <p class="btn_cancel"><%= link_to "キャンセル", :back, class: "btn btn-light" %></p>
    </div>
  </div>
<% end %>

</div>

<script type="text/javascript">
$(function() {
    $('input[type=radio]').change(function() {
        $('#tr1,#tr2').removeClass('invisible');
        if ($("input:radio[class='lost_or_rescued']:checked").val() == "迷子") {
            $('#tr2').addClass('invisible');
            $('#tr2 .form-control').prop('disabled', true);
            $('#tr1 .form-control').prop('disabled', false);
        } else if($("input:radio[class='lost_or_rescued']:checked").val() == "保護") {
            $('#tr1').addClass('invisible');
            $('#tr1 .form-control').prop('disabled', true);
            $('#tr2 .form-control').prop('disabled', false);
        }
    }).trigger('change'); //←(1)
});
</script>

app/views/pets/show.html.erb
<div class="col-sm-12 label">
  <div id="breadcrumb">
    <% breadcrumb :pet_show %>
    <%= render "shared/breadcrumbs" %>
  </div>
  <% if @pet.status == "迷子" %>
    <h2 class="status status_lost">迷子</h2>
  <% elsif @pet.status == "保護" %>
    <h2 class="status status_find">保護</h2>
  <% end %>
</div>

<div class="col-sm-12 col-md-5">
  <%= image_tag(@pet.image.url, class: "img-fluid") %>
</div>
<div class="col-sm-12 col-md-7">

  <% if user_signed_in? %>
    <% if @user.id == current_user.id %>
      <%= link_to "編集", edit_pet_path(@pet.id),class: "btn btn-info" %>　
      <%= link_to "削除", pet_path(@pet.id),class: "btn btn-light", data: { confirm: "本当に削除してもよろしいですか？" }, method: :delete %>
    <% end %>
  <% end %>

  <% if @pet.status == "迷子" %>
    <p class="name">名前：<%= @pet.name %></p>
    <p class="kind">種類：<%= @pet.kind %></p>
    <p class="kind">迷子になった日：<%= @pet.lost_day.strftime("%Y年%m月%d日") %></p>
    <p class="kind">性別：<%= @pet.lost_gender %></p>
    <p class="feature"><%= @pet.feature %> <small>by <%= @pet.user.nickname %>さん</small></p>
  <% elsif @pet.status == "保護" %>
    <p class="kind">種類：<%= @pet.kind %></p>
    <p class="kind">保護した日：<%= @pet.find_day.strftime("%Y年%m月%d日") %></p>
    <p class="kind">性別：<%= @pet.find_gender %></p>
    <p class="feature"><%= @pet.feature %> <small>by <%= @pet.user.nickname %>さん</small></p>
  <% end %>
  <% if user_signed_in? %>
    <% unless @user.id == current_user.id %>
      <% if @isRoom == true %>
        <p><a href="/rooms/<%= @roomId %>" class="btn btn-info">メッセージを送る</a>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, value: @user.id %>
          <% end %>
          <%= f.submit "メッセージを送る", class: "btn btn-info" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <% unless user_signed_in? %>
    <a href="/rooms/<%= @roomId %>" class="btn btn-info">メッセージを送る</a>
  <% end %>
</div>

<div class="col-sm-12">
  <p><div id="map"></div></p>
  <% if @pet.status == "迷子" %>
    <p><i class="material-icons-round">place</i>迷子になった場所：<%= @pet.area %></p>
  <% elsif @pet.status == "保護" %>
    <p><i class="material-icons-round">place</i>保護した場所：<%= @pet.area %></p>
  <% end %>

  <script type="text/javascript">
      function initMap() {

          var test ={lat: <%= @pet.latitude %>, lng: <%= @pet.longitude %>};
          var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
          });
          var transitLayer = new google.maps.TransitLayer();
          transitLayer.setMap(map);

          var contentString = '住所：<%= @pet.area %>';
          var infowindow = new google.maps.InfoWindow({
              content: contentString
          });

          var marker = new google.maps.Marker({
              position:test,
              map: map,
              title: contentString
          });

          marker.addListener('click', function() {
              infowindow.open(map, marker);
          });
      }
  </script>
  <script async defer
          src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
  </script>

</div>