config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root "pets#index"
  resources :pets
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :rooms, only: [:create, :show, :index]
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def index
    @currentEntries = current_user.entries
    myRoomIds = []
    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
    @user = current_user
    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?',@user.id)
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages.includes(:user)
      @message = Message.new
      @entries = @room.entries.includes(:user)
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="col-sm-12" id="room-page">
  <div id="breadcrumb">
    <% breadcrumb :rooms %>
    <%= render "shared/breadcrumbs" %>
  </div>
  <% if @anotherEntries.count == 0 %>
    <p>メッセージがありません。</p>
  <% end %>
  <% @anotherEntries.each do |e| %>
    <% if e.room.messages.present? %>
    <div class="message-box">
      <%= link_to room_path(e.room.id) do %>
        <p><%= e.user.nickname %>さん</p>
        <p><%= e.room.messages.last.content %></p>
        <p><%= e.room.messages.last.created_at.strftime("%Y年%m月%d日 %H:%M") %></p>
      <% end %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="col-xs-12" id="room-page">
<div id="breadcrumb">
  <% breadcrumb :room_show %>
  <%= render "shared/breadcrumbs" %>
</div>
<h1>メッセージ</h1>
<h4>参加者</h4>
<% @entries.each do |e| %>
  <h5><strong><%= e.user.nickname%><% unless current_user.id == e.user_id %>さん<% end %></strong></h5>
<% end %>

<hr>
<% if @messages.present? %>
  <% @messages.each do |m| %>
    <strong><%= m.content %></strong> <small>by <strong><%= m.user.nickname %><% unless current_user.id == m.user_id %>さん<% end %></strong></small>
    <% if current_user.id == m.user_id %>
      <div class="btn_message clearfix">
　      <%= button_to "編集", edit_message_path(m.id), method: :get %>　<%= button_to("削除", message_path(m.id),method: :delete) %>
      </div>
    <% end %>
    <hr>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>

<%= form_for @message do |f| %>
  <%= f.text_field :content, placeholder: "メッセージを入力して下さい。空白の場合メッセージは送信されません。" , size: 70 %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <br>
  <%= f.submit "投稿する", class: "btn btn-info" %>
<% end %>

</div>