config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root "pets#index"
  resources :pets
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :rooms, only: [:create, :show, :index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lostbird</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&family=Paytone+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons+Round" rel="stylesheet">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-green mr-auto">
      <div class="container">
        <p id = "logo"><%= link_to "lostbird", pets_path %></p>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
            <p><%= link_to "メッセージ一覧", rooms_path, class: "nav-item nav-link" %></p>
            <p><%= link_to current_user.nickname, user_path(current_user.id), class: "nav-item nav-link" %></p>
            <% else %>
              <%= link_to "ユーザー登録", new_user_registration_path, class: "nav-item nav-link" %>
              <br>
              <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link" %>
            <% end %>
          </ul>
        </div>

      </div>
    </nav>

    <div class="container">
      <div class="row">
        <% flash.each do |key, value| %>
          <p><%= content_tag(:p, value, class: "alert alert-#{key}") %></p>
        <% end %>

        <%= yield %>
      </div>
    </div>

  </body>
</html>